version: "3.9"
services:
  ingester:
    # build:
    #   context: ./src
    #   dockerfile: .
    image: landscapedatacommons/ingester:latest
    stdin_open: true 
    tty: true        
    container_name: ingester
    volumes:
      - ./dimas:/usr/src/dimas:cached
# docker-compose build
# docker-compose run --rm ingester